<?php
// function bakery_user_menu() {
//
//     $items['welcome'] = array(
//         'title' => 'GuestBook!',
//         'page callback' => 'bakery_user_user_login',
//         'access callback' => TRUE,
//         'type' => MENU_CALLBACK,
//
//     );
//     return $items;
// }

function bakery_user_user_login(&$edit, $account) {
    $redirection = 'welcome_new_user';
    $_GET['destination'] = $redirection;
}
