<?php
function bakery_user_menu() {
    $items['welcome'] = array(
        'title' => 'Hi There!',
        'page callback' => 'bakery_user_user_login',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function bakery_user_user_login(&$edit, $account) {
    $redirection = 'welcome';
    $_GET['destination'] = $redirection;
    // $edit['redirect'] = 'welcome_new_user';
}
